In [1]:
import numpy as np

In [3]:
# All elements of array must be of same type
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [4]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [6]:
array1.dtype

dtype('int64')

In [7]:
# Multi-dimensional arrays
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [9]:
# Can be used as placeholder values, since resizing an array is expensive
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [10]:
# Analagous to `range` function in std Python
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# 'Reshapes' an array to a given dimension
np.arange(100).reshape((10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [12]:
# Scalar Math - performed *elementwise*
5 * np.ones(10).reshape(5,2)

array([[ 5.,  5.],
       [ 5.,  5.],
       [ 5.,  5.],
       [ 5.,  5.],
       [ 5.,  5.]])

In [13]:
a = np.arange(10)
a > 5

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [17]:
np.random.random((5,5))

array([[ 0.95298352,  0.90345134,  0.13066334,  0.18533891,  0.03220615],
       [ 0.16696741,  0.20431751,  0.35936079,  0.89533088,  0.23497618],
       [ 0.009106  ,  0.53723214,  0.36206403,  0.41899684,  0.70430916],
       [ 0.40186799,  0.33021927,  0.26750689,  0.43950555,  0.31990656],
       [ 0.46483606,  0.67949712,  0.37571277,  0.86197186,  0.23078798]])

In [18]:
np.arange(10).sum()

45

In [19]:
np.arange(10).min()
np.arange(10).max()

9

In [21]:
array2 = np.arange(20).reshape((5,4))
array2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [26]:
# Sum of each row 
array2.sum(axis=1)

array([ 6, 22, 38, 54, 70])

In [24]:
# The max in each column
array2.max(axis=0) 

array([16, 17, 18, 19])