In [2]:
import numpy as np

In [20]:
array = np.arange(10)**2
array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
# 1-D Slicing
array[:2]

array([0, 1])

In [14]:
# Selects elements 2-10, exclusive, stepping by 2
array[2:10:2]

array([ 4, 16, 36, 64])

In [15]:
# Set every other element to 100
array[::2] = 100
array

array([100,   1, 100,   9, 100,  25, 100,  49, 100,  81])